# Generated by Django 5.0.1 on 2024-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spicy', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
